### ISSUE TITLE
Graph does not update unless server is restarted?

### ISSUE THREAD

**Issue by nspassov** [altangent/lightning-viz#11]
I run lightning-viz connected to my lnd litecoin client and it seems like the graph (and the numbers on top) is only being created once and is not being updated unless the server is restarted. Have I misconfigured something or is this intended?

**Comment by bmancini55** [comment]
To speed up rendering in the browser, it pre-builds the D3 graph on the server. It does this operation every minute as defined here:
https://github.com/altangent/lightning-viz/blob/master/src/server/apis/api-network.js

When this happens you should see logged info in the console such as:
```bash
info: load graph durationMs=15402
info: load graph durationMs=15459
info: load graph durationMs=15003
info: load graph durationMs=15066
info: load graph durationMs=14930
```

Can you verify that these updates are in the console? Can you verify that nothing has updated after  refreshing the browser after a minute?

**Comment by nspassov** [comment]
I had disabled the logging since I've been running it as a deamon. It seems like in the Litecoin LN network there is less activity, which has given me the impression that the graph is cached for longer.

Thanks for your response!
